# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6a8f0030e22ad3e24bcedf12044aafb1c99713912f7a1fd3fd5b62a6306a7fd34a0c68c82370292afc050cabf31e7b49c4f058313a3b65456e31db0c771e4ed

test:
  secret_key_base: a68c491d3347c1cd73d96cb5816a0e1af0c803603887d3d51e66476814e1d60d17737b1514f89a1e92f96341a6133734ea2f5aabc4f302c8d94086e78ac1e111

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
